-- Full menu replacement — all items from restaurantimperial.be
-- Replaces placeholder data with the complete real menu (111 items, 14 categories)

BEGIN;

-- ── 1. Clear existing placeholder data ──────────────────────────────────────
DELETE FROM imperial_item_translations;
DELETE FROM imperial_items;
DELETE FROM imperial_category_translations;
DELETE FROM imperial_categories;

-- ── 2. Categories ────────────────────────────────────────────────────────────
INSERT INTO imperial_categories (id, sort_order) OVERRIDING SYSTEM VALUE VALUES
  (1,  1),  -- Soupes
  (2,  2),  -- Salades
  (3,  3),  -- Dim Sum
  (4,  4),  -- Entrées Chaudes
  (5,  5),  -- Poulet
  (6,  6),  -- Boeuf
  (7,  7),  -- Porc
  (8,  8),  -- Canard
  (9,  9),  -- Scampis
  (10, 10), -- Fruits de Mer
  (11, 11), -- Ti-Pan
  (12, 12), -- Cassolettes
  (13, 13), -- Riz
  (14, 14); -- Nouilles

SELECT setval('imperial_categories_id_seq', 14);

INSERT INTO imperial_category_translations (category_id, locale, name) VALUES
  (1,  'fr', 'Soupes'),                 (1,  'nl', 'Soepen'),                   (1,  'en', 'Soups'),
  (2,  'fr', 'Salades'),                (2,  'nl', 'Salades'),                   (2,  'en', 'Salads'),
  (3,  'fr', 'Dim Sum'),                (3,  'nl', 'Dim Sum'),                   (3,  'en', 'Dim Sum'),
  (4,  'fr', 'Entrées Chaudes'),        (4,  'nl', 'Warme Voorgerechten'),       (4,  'en', 'Hot Appetizers'),
  (5,  'fr', 'Poulet'),                 (5,  'nl', 'Kip'),                       (5,  'en', 'Chicken'),
  (6,  'fr', 'Boeuf'),                  (6,  'nl', 'Rund'),                      (6,  'en', 'Beef'),
  (7,  'fr', 'Porc'),                   (7,  'nl', 'Varken'),                    (7,  'en', 'Pork'),
  (8,  'fr', 'Canard'),                 (8,  'nl', 'Eend'),                      (8,  'en', 'Duck'),
  (9,  'fr', 'Scampis'),                (9,  'nl', 'Scampi'),                    (9,  'en', 'Scampi'),
  (10, 'fr', 'Fruits de Mer'),          (10, 'nl', 'Zeevruchten'),               (10, 'en', 'Seafood'),
  (11, 'fr', 'Ti-Pan'),                 (11, 'nl', 'Ti-Pan'),                    (11, 'en', 'Ti-Pan'),
  (12, 'fr', 'Cassolettes'),            (12, 'nl', 'Casseroles'),                (12, 'en', 'Casseroles'),
  (13, 'fr', 'Riz'),                    (13, 'nl', 'Rijst'),                     (13, 'en', 'Rice'),
  (14, 'fr', 'Nouilles'),               (14, 'nl', 'Noedels'),                   (14, 'en', 'Noodles');

-- ── 3. Items ─────────────────────────────────────────────────────────────────
-- Columns: id, category_id, num, price_restaurant, price_takeaway, sort_order, active, is_featured
INSERT INTO imperial_items (id, category_id, num, price_restaurant, price_takeaway, sort_order, active, is_featured) OVERRIDING SYSTEM VALUE VALUES
  -- SOUPES (cat 1)
  (1,  1, '01', 8.50, 8.50, 1,  true, false),
  (2,  1, '02', 7.50, 7.50, 2,  true, false),
  (3,  1, '03', 7.00, 7.00, 3,  true, false),
  (4,  1, '04', 7.00, 7.00, 4,  true, false),
  (5,  1, '05', 6.50, 6.50, 5,  true, false),
  (6,  1, '06', 6.50, 6.50, 6,  true, false),
  (7,  1, '07', 6.50, 6.50, 7,  true, false),
  (8,  1, '08', 6.50, 6.50, 8,  true, false),
  -- SALADES (cat 2)
  (9,  2, '10', 8.50,  8.50, 1, true, false),
  (10, 2, '11', 11.00, 11.00, 2, true, false),
  (11, 2, '12', 11.00, 11.00, 3, true, false),
  (12, 2, '13', 7.00,  7.00, 4, true, false),
  -- DIM SUM (cat 3)
  (13, 3, '15', 9.00, 9.00, 1, true, false),
  (14, 3, '16', 9.00, 9.00, 2, true, false),
  (15, 3, '17', 7.50, 7.50, 3, true, false),
  (16, 3, '18', 7.50, 7.50, 4, true, false),
  -- ENTRÉES CHAUDES (cat 4)
  (17, 4, '20', 8.00,  8.00, 1,  true, false),
  (18, 4, '21', 12.00, 12.00, 2, true, false),
  (19, 4, '22', 12.00, 12.00, 3, true, false),
  (20, 4, '23', 8.00,  8.00, 4,  true, false),
  (21, 4, '24', 8.00,  8.00, 5,  true, false),
  (22, 4, '25', 11.00, 11.00, 6, true, false),
  (23, 4, '26', 9.00,  9.00, 7,  true, false),
  (24, 4, '27', 7.00,  7.00, 8,  true, false),
  (25, 4, '28', 8.00,  8.00, 9,  true, false),
  (26, 4, '29', 6.50,  6.50, 10, true, false),
  (27, 4, '30', 9.50,  9.50, 11, true, false),
  (28, 4, '31', 11.50, 11.50, 12, true, false),
  (29, 4, '32', 12.00, 12.00, 13, true, false),
  (30, 4, '33', 16.00, 16.00, 14, true, false),
  (31, 4, '34', 10.50, 10.50, 15, true, false),
  (32, 4, '35', 7.50,  7.50, 16, true, false),
  -- POULET (cat 5)
  (33, 5, '40', 15.50, 15.50, 1,  true, false),
  (34, 5, '41', 15.50, 15.50, 2,  true, false),
  (35, 5, '42', 15.50, 15.50, 3,  true, false),
  (36, 5, '43', 15.50, 15.50, 4,  true, false),
  (37, 5, '44', 15.50, 15.50, 5,  true, false),
  (38, 5, '45', 15.50, 15.50, 6,  true, false),
  (39, 5, '46', 15.50, 15.50, 7,  true, false),
  (40, 5, '47', 16.50, 16.50, 8,  true, false),
  (41, 5, '48', 16.50, 16.50, 9,  true, false),
  (42, 5, '49', 16.50, 16.50, 10, true, false),
  -- BOEUF (cat 6)
  (43, 6, '50', 16.50, 16.50, 1, true, false),
  (44, 6, '51', 16.50, 16.50, 2, true, false),
  (45, 6, '52', 16.50, 16.50, 3, true, false),
  (46, 6, '53', 16.50, 16.50, 4, true, false),
  (47, 6, '54', 16.50, 16.50, 5, true, false),
  (48, 6, '55', 16.50, 16.50, 6, true, false),
  (49, 6, '56', 16.50, 16.50, 7, true, false),
  (50, 6, '57', 16.50, 16.50, 8, true, false),
  -- PORC (cat 7)
  (51, 7, '60', 15.50, 15.50, 1, true, false),
  (52, 7, '61', 15.50, 15.50, 2, true, false),
  (53, 7, '62', 15.50, 15.50, 3, true, false),
  (54, 7, '63', 15.50, 15.50, 4, true, false),
  (55, 7, '64', 15.50, 15.50, 5, true, false),
  (56, 7, '65', 15.50, 15.50, 6, true, false),
  (57, 7, '66', 15.50, 15.50, 7, true, false),
  (58, 7, '67', 17.50, 17.50, 8, true, false),
  (59, 7, '68', 19.50, 19.50, 9, true, false),
  -- CANARD (cat 8)
  (60, 8, '70', 22.00, 22.00, 1, true, false),
  (61, 8, '71', 22.00, 22.00, 2, true, false),
  (62, 8, '72', 22.00, 22.00, 3, true, false),
  (63, 8, '73', 22.00, 22.00, 4, true, false),
  (64, 8, '74', 22.00, 22.00, 5, true, false),
  (65, 8, '75', 22.00, 22.00, 6, true, false),
  -- SCAMPIS (cat 9)
  (66, 9, '80', 19.50, 19.50, 1, true, false),
  (67, 9, '81', 19.50, 19.50, 2, true, false),
  (68, 9, '82', 19.50, 19.50, 3, true, false),
  (69, 9, '83', 19.50, 19.50, 4, true, false),
  (70, 9, '84', 19.50, 19.50, 5, true, false),
  (71, 9, '85', 19.50, 19.50, 6, true, false),
  (72, 9, '86', 19.50, 19.50, 7, true, false),
  (73, 9, '87', 19.50, 19.50, 8, true, false),
  -- FRUITS DE MER (cat 10)
  (74, 10, '90', 16.50, 16.50, 1,  true, false),
  (75, 10, '91', 16.50, 16.50, 2,  true, false),
  (76, 10, '92', 24.00, 24.00, 3,  true, false),
  (77, 10, '93', 24.00, 24.00, 4,  true, false),
  (78, 10, '94', 34.00, 34.00, 5,  true, false),
  (79, 10, '95', 34.00, 34.00, 6,  true, false),
  (80, 10, '96', 28.00, 28.00, 7,  true, false),
  (81, 10, '97', 28.00, 28.00, 8,  true, false),
  (82, 10, '98', 22.00, 22.00, 9,  true, false),
  (83, 10, '99', 22.00, 22.00, 10, true, false),
  -- TI-PAN (cat 11)
  (84, 11, '100', 18.00, 18.00, 1, true, false),
  (85, 11, '101', 19.00, 19.00, 2, true, false),
  (86, 11, '102', 20.00, 20.00, 3, true, false),
  (87, 11, '103', 22.50, 22.50, 4, true, false),
  (88, 11, '104', 22.00, 22.00, 5, true, false),
  (89, 11, '105', 18.00, 18.00, 6, true, false),
  (90, 11, '106', 22.00, 22.00, 7, true, false),
  -- CASSOLETTES (cat 12)
  (91, 12, '110', 18.50, 18.50, 1, true, false),
  (92, 12, '111', 19.50, 19.50, 2, true, false),
  (93, 12, '112', 18.50, 18.50, 3, true, false),
  (94, 12, '113', 22.50, 22.50, 4, true, false),
  (95, 12, '114', 21.00, 21.00, 5, true, false),
  (96, 12, '115', 20.00, 20.00, 6, true, false),
  (97, 12, '116', 16.00, 16.00, 7, true, false),
  -- RIZ (cat 13)
  (98,  13, '120', 15.00, 15.00, 1, true, false),
  (99,  13, '121', 16.00, 16.00, 2, true, false),
  (100, 13, '122', 18.00, 18.00, 3, true, false),
  (101, 13, '123', 18.00, 18.00, 4, true, false),
  (102, 13, '124', 15.00, 15.00, 5, true, false),
  (103, 13, '125', 18.00, 18.00, 6, true, false),
  (104, 13, '126', 9.00,  9.00, 7, true, false),
  -- NOUILLES (cat 14)
  (105, 14, '130', 15.00, 15.00, 1, true, false),
  (106, 14, '131', 16.00, 16.00, 2, true, false),
  (107, 14, '132', 18.00, 18.00, 3, true, false),
  (108, 14, '133', 18.00, 18.00, 4, true, false),
  (109, 14, '134', 15.00, 15.00, 5, true, false),
  (110, 14, '135', 18.00, 18.00, 6, true, false),
  (111, 14, '136', 9.00,  9.00, 7, true, false);

SELECT setval('imperial_items_id_seq', 111);

-- ── 4. Item translations ─────────────────────────────────────────────────────
INSERT INTO imperial_item_translations (item_id, locale, name, description) VALUES
  -- SOUPS
  (1,  'fr', 'Soupe Tom Yan Kung (épicée)',         'Soupe de crevettes épicée à la thaïlandaise'),
  (1,  'nl', 'Tom Yan Kung soep (pikant)',           'Thaise pikante garnalensoep'),
  (1,  'en', 'Tom Yan Kung soup (spicy)',            'Spicy Thai prawn soup'),
  (2,  'fr', 'Soupe Tom Kha Khai (épicée)',          'Soupe au lait de coco et poulet'),
  (2,  'nl', 'Tom Kha Khai soep (pikant)',           'Kokosmelksoep met kip'),
  (2,  'en', 'Tom Kha Khai soup (spicy)',            'Coconut milk and chicken soup'),
  (3,  'fr', 'Soupe Wan Tan',                        'Raviolis chinois en bouillon parfumé'),
  (3,  'nl', 'Wan Tan soep',                         'Chinese dumplings in geurige bouillon'),
  (3,  'en', 'Wan Tan soup',                         'Chinese ravioli in fragrant broth'),
  (4,  'fr', 'Soupe de fruits de mer',               'Fruits de mer variés en bouillon'),
  (4,  'nl', 'Zeevruchtensoep',                      'Gevarieerde zeevruchten in bouillon'),
  (4,  'en', 'Seafood soup',                         'Assorted seafood in broth'),
  (5,  'fr', 'Soupe de poulet aux vermicelles',      'Poulet et vermicelles fins en bouillon'),
  (5,  'nl', 'Kippensoep met dunne noedels',         'Kip en dunne noedels in bouillon'),
  (5,  'en', 'Chicken soup with thin noodles',       'Chicken and thin noodles in broth'),
  (6,  'fr', 'Soupe épicée',                         'Bouillon épicé aux légumes et viande'),
  (6,  'nl', 'Pikante soep',                         'Pikante bouillon met groenten en vlees'),
  (6,  'en', 'Spicy soup',                           'Spicy broth with vegetables and meat'),
  (7,  'fr', 'Soupe de tomate au poulet',            'Bouillon de tomate au poulet'),
  (7,  'nl', 'Tomatensoep met kip',                  'Tomatenbouillon met kip'),
  (7,  'en', 'Tomato soup with chicken',             'Tomato broth with chicken'),
  (8,  'fr', 'Soupe nid d''hirondelle',              'Soupe traditionnelle au nid d''hirondelle'),
  (8,  'nl', 'Zwaluwnestensoep',                     'Traditionele soep met zwaluwnestenextract'),
  (8,  'en', 'Bird''s nest soup',                    'Traditional bird''s nest soup'),
  -- SALADS
  (9,  'fr', 'Salade de poulet',                     'Salade fraîche au poulet'),
  (9,  'nl', 'Kipsalade',                            'Frisse salade met kip'),
  (9,  'en', 'Chicken salad',                        'Fresh salad with chicken'),
  (10, 'fr', 'Salade de crabe',                      'Salade fraîche au crabe'),
  (10, 'nl', 'Krabsalade',                           'Frisse salade met krab'),
  (10, 'en', 'Crab salad',                           'Fresh salad with crab'),
  (11, 'fr', 'Salade de scampis',                    'Salade fraîche aux scampis'),
  (11, 'nl', 'Scampisalade',                         'Frisse salade met scampi'),
  (11, 'en', 'Scampi salad',                         'Fresh salad with scampi'),
  (12, 'fr', 'Salade végétarienne',                  'Salade fraîche aux légumes variés'),
  (12, 'nl', 'Vegetarische salade',                  'Frisse salade met gevarieerde groenten'),
  (12, 'en', 'Vegetarian salad',                     'Fresh salad with assorted vegetables'),
  -- DIM SUM
  (13, 'fr', 'Dim Sum vapeur, 4 variétés',           'Sélection de 4 variétés vapeur'),
  (13, 'nl', 'Gestoomde Dim Sum, 4 variëteiten',     'Selectie van 4 gestoomde variëteiten'),
  (13, 'en', 'Steamed dim sum, 4 varieties',         'Selection of 4 steamed varieties'),
  (14, 'fr', 'Dim Sum vapeur aux crevettes',         'Dim sum vapeur garnis de crevettes'),
  (14, 'nl', 'Gestoomde Dim Sum met garnalen',       'Gestoomde dim sum gevuld met garnalen'),
  (14, 'en', 'Steamed dim sum with shrimp',          'Steamed dim sum filled with shrimp'),
  (15, 'fr', 'Dim Sum vapeur au porc',               'Dim sum vapeur garnis de porc'),
  (15, 'nl', 'Gestoomde Dim Sum met varken',         'Gestoomde dim sum gevuld met varken'),
  (15, 'en', 'Steamed dim sum with pork',            'Steamed dim sum filled with pork'),
  (16, 'fr', 'Dim Sum vapeur au bœuf',               'Dim sum vapeur garnis de bœuf'),
  (16, 'nl', 'Gestoomde Dim Sum met rund',           'Gestoomde dim sum gevuld met rundvlees'),
  (16, 'en', 'Steamed dim sum with beef',            'Steamed dim sum filled with beef'),
  -- HOT APPETIZERS
  (17, 'fr', 'Rouleaux de printemps',                'Rouleaux croustillants aux légumes et vermicelles'),
  (17, 'nl', 'Loempia''s',                           'Krokante loempia''s met groenten en glasmie'),
  (17, 'en', 'Spring rolls',                         'Crispy spring rolls with vegetables and vermicelli'),
  (18, 'fr', 'Triangles de l''amour',                'Poulet en feuille de bananier'),
  (18, 'nl', 'Liefdesdriehoekjes',                   'Kip in bananenblad'),
  (18, 'en', '"Triangles of love"',                  'Chicken wrapped in banana leaf'),
  (19, 'fr', 'Brochettes impériales',                'Brochettes assorties poulet, porc et scampis'),
  (19, 'nl', 'Imperiale spiesjes',                   'Gemengde spiesjes kip, varken en scampi'),
  (19, 'en', 'Imperial skewers',                     'Assorted chicken, pork and scampi skewers'),
  (20, 'fr', 'Brochettes de porc',                   'Brochettes de porc marinées et grillées'),
  (20, 'nl', 'Varkensspiesjes',                      'Gemarineerde en gegrilde varkensspiesjes'),
  (20, 'en', 'Pork skewers',                         'Marinated and grilled pork skewers'),
  (21, 'fr', 'Brochettes de poulet',                 'Brochettes de poulet marinées et grillées'),
  (21, 'nl', 'Kipspiesjes',                          'Gemarineerde en gegrilde kipspiesjes'),
  (21, 'en', 'Chicken skewers',                      'Marinated and grilled chicken skewers'),
  (22, 'fr', 'Brochettes de scampis',                'Brochettes de scampis grillées'),
  (22, 'nl', 'Scampispiesjes',                       'Gegrilde scampispiesjes'),
  (22, 'en', 'Scampi skewers',                       'Grilled scampi skewers'),
  (23, 'fr', 'Nems (4 pièces)',                      'Rouleaux frits farcis à la viande et légumes'),
  (23, 'nl', 'Nems (4 stuks)',                       'Gebakken rolletjes gevuld met vlees en groenten'),
  (23, 'en', 'Nems (4 pieces)',                      'Fried rolls stuffed with meat and vegetables'),
  (24, 'fr', 'Wontons frits',                        'Raviolis chinois frits'),
  (24, 'nl', 'Gebakken wontons',                     'Gebakken Chinese dumplings'),
  (24, 'en', 'Fried wontons',                        'Crispy fried Chinese dumplings'),
  (25, 'fr', 'Entrées maison',                       'Assortiment nems, wontons, funco et triangles au curry'),
  (25, 'nl', 'Huisentrees',                          'Assortiment nems, wontons, funco en currydriehoekes'),
  (25, 'en', 'House appetizers',                     'Assortment of nems, wontons, funco and curry triangles'),
  (26, 'fr', 'Triangles au curry',                   'Pâte frite farcie au curry de viande'),
  (26, 'nl', 'Currydriehoekes',                      'Gefrituurde deeg gevuld met vlees en curry'),
  (26, 'en', 'Curry triangles',                      'Fried pastry filled with curried meat'),
  (27, 'fr', 'Beignets de scampis sauce aigre-douce','Scampis en tempura, sauce aigre-douce'),
  (27, 'nl', 'Scampibeignets zoetzure saus',         'Scampi in tempura, zoetzure saus'),
  (27, 'en', 'Scampi fritters with sweet-sour sauce','Scampi in tempura batter, sweet and sour sauce'),
  (28, 'fr', 'Scampis au beurre d''ail',             'Scampis sautées au beurre et à l''ail'),
  (28, 'nl', 'Scampi in knoflookboter',              'Scampi gebakken in boter en knoflook'),
  (28, 'en', 'Scampis in garlic butter',             'Scampi sautéed in garlic butter'),
  (29, 'fr', 'Cuisses de grenouilles au beurre d''ail', 'Cuisses de grenouilles sautées au beurre et à l''ail'),
  (29, 'nl', 'Kikkerbillen met boter en knoflook',   'Kikkerbillen gebakken in boter en knoflook'),
  (29, 'en', 'Frog legs with butter and garlic',     'Frog legs sautéed in garlic butter'),
  (30, 'fr', 'Coquilles St. Jacques sautées au beurre d''ail', 'St. Jacques poêlées au beurre et à l''ail'),
  (30, 'nl', 'Coquilles St. Jacques in knoflookboter', 'St. Jacques gebakken in boter en knoflook'),
  (30, 'en', 'St. Jacques scallops sautéed in garlic butter', 'Scallops pan-fried in garlic butter'),
  (31, 'fr', 'Travers de porc rôtis',                'Côtes de porc marinées et rôties'),
  (31, 'nl', 'Geroosterde varkensribbetjes',          'Gemarineerde en geroosterde varkensribbetjes'),
  (31, 'en', 'Roasted pork ribs',                    'Marinated and roasted pork ribs'),
  (32, 'fr', 'Beignets de funco frits',               'Beignets de crevettes séchées frits'),
  (32, 'nl', 'Gebakken funco beignets',               'Gefrituurde garnalenbeignets'),
  (32, 'en', 'Fried funco fritters',                  'Crispy dried shrimp fritters'),
  -- CHICKEN
  (33, 'fr', 'Poulet au basilic',                    'Poulet sauté au basilic frais et sauce aux huîtres'),
  (33, 'nl', 'Kip met basilicum',                    'Gebakken kip met verse basilicum en oestersaus'),
  (33, 'en', 'Chicken with basil',                   'Stir-fried chicken with fresh basil and oyster sauce'),
  (34, 'fr', 'Chop Suey au poulet',                  'Poulet sauté aux légumes variés à la chinoise'),
  (34, 'nl', 'Chop Suey met kip',                    'Roergebakken kip met diverse groenten'),
  (34, 'en', 'Chop suey with chicken',               'Stir-fried chicken with assorted vegetables'),
  (35, 'fr', 'Poulet aux champignons chinois',        'Poulet sauté aux champignons noirs'),
  (35, 'nl', 'Kip met Chinese paddenstoelen',         'Roergebakken kip met zwarte paddenstoelen'),
  (35, 'en', 'Chicken with Chinese mushrooms',        'Stir-fried chicken with black mushrooms'),
  (36, 'fr', 'Poulet à la sauce épicée',              'Poulet sauté en sauce pimentée'),
  (36, 'nl', 'Kip met pikante saus',                  'Roergebakken kip in pittige saus'),
  (36, 'en', 'Chicken with spicy sauce',              'Stir-fried chicken in spicy sauce'),
  (37, 'fr', 'Poulet à la sauce au curry',            'Poulet sauté en sauce au curry'),
  (37, 'nl', 'Kip met currysaus',                     'Roergebakken kip in currysaus'),
  (37, 'en', 'Chicken with curry sauce',              'Stir-fried chicken in curry sauce'),
  (38, 'fr', 'Poulet aux légumes mélangés',           'Poulet sauté aux légumes frais variés'),
  (38, 'nl', 'Kip met gemengde groenten',              'Roergebakken kip met verse gemengde groenten'),
  (38, 'en', 'Chicken with mixed vegetables',         'Stir-fried chicken with fresh mixed vegetables'),
  (39, 'fr', 'Poulet à l''ananas',                    'Poulet sauté à l''ananas frais'),
  (39, 'nl', 'Kip met ananas',                        'Roergebakken kip met verse ananas'),
  (39, 'en', 'Chicken with pineapple',                'Stir-fried chicken with fresh pineapple'),
  (40, 'fr', 'Filet de poulet frit style malaisien',  'Filet de poulet frit à la malaisienne'),
  (40, 'nl', 'Gefrituurde kipfilet Maleisische stijl','Gefrituurde kipfilet op Maleisische wijze'),
  (40, 'en', 'Fried chicken fillet Malaysian style',  'Fried chicken fillet in Malaysian style'),
  (41, 'fr', 'Beignet de poulet à l''ananas sauce aigre-douce', 'Poulet frit, ananas, sauce aigre-douce'),
  (41, 'nl', 'Kipbeignet met ananas en zoetzure saus', 'Gefrituurde kip, ananas, zoetzure saus'),
  (41, 'en', 'Chicken fritter with pineapple, sweet-sour sauce', 'Fried chicken with pineapple and sweet and sour sauce'),
  (42, 'fr', 'Poulet à la sauce citronnée',           'Poulet sauté à la sauce au citron'),
  (42, 'nl', 'Kip met citroensaus',                   'Roergebakken kip met citroensaus'),
  (42, 'en', 'Chicken with lemon sauce',              'Stir-fried chicken in lemon sauce'),
  -- BEEF
  (43, 'fr', 'Bœuf au basilic',                      'Bœuf sauté au basilic frais et sauce aux huîtres'),
  (43, 'nl', 'Rund met basilicum',                    'Roergebakken rund met verse basilicum en oestersaus'),
  (43, 'en', 'Beef with basil',                       'Stir-fried beef with fresh basil and oyster sauce'),
  (44, 'fr', 'Chop Suey au bœuf',                    'Bœuf sauté aux légumes variés à la chinoise'),
  (44, 'nl', 'Chop Suey met rund',                    'Roergebakken rund met diverse groenten'),
  (44, 'en', 'Chop suey with beef',                   'Stir-fried beef with assorted vegetables'),
  (45, 'fr', 'Bœuf aux champignons chinois',          'Bœuf sauté aux champignons noirs'),
  (45, 'nl', 'Rund met Chinese paddenstoelen',         'Roergebakken rund met zwarte paddenstoelen'),
  (45, 'en', 'Beef with Chinese mushrooms',           'Stir-fried beef with black mushrooms'),
  (46, 'fr', 'Bœuf à la sauce épicée',               'Bœuf sauté en sauce pimentée'),
  (46, 'nl', 'Rund met pikante saus',                  'Roergebakken rund in pittige saus'),
  (46, 'en', 'Beef with spicy sauce',                 'Stir-fried beef in spicy sauce'),
  (47, 'fr', 'Bœuf à la sauce au curry',             'Bœuf sauté en sauce au curry'),
  (47, 'nl', 'Rund met currysaus',                     'Roergebakken rund in currysaus'),
  (47, 'en', 'Beef with curry sauce',                 'Stir-fried beef in curry sauce'),
  (48, 'fr', 'Bœuf aux légumes mélangés',            'Bœuf sauté aux légumes frais variés'),
  (48, 'nl', 'Rund met gemengde groenten',              'Roergebakken rund met verse gemengde groenten'),
  (48, 'en', 'Beef with mixed vegetables',            'Stir-fried beef with fresh mixed vegetables'),
  (49, 'fr', 'Bœuf aux oignons',                     'Bœuf sauté aux oignons'),
  (49, 'nl', 'Rund met uien',                          'Roergebakken rund met uien'),
  (49, 'en', 'Beef with onions',                      'Stir-fried beef with onions'),
  (50, 'fr', 'Bœuf à la citronnelle',                'Bœuf sauté à la citronnelle'),
  (50, 'nl', 'Rund met citroengras',                   'Roergebakken rund met citroengras'),
  (50, 'en', 'Beef with lemongrass',                  'Stir-fried beef with lemongrass'),
  -- PORK
  (51, 'fr', 'Porc au basilic',                       'Porc sauté au basilic frais et sauce aux huîtres'),
  (51, 'nl', 'Varken met basilicum',                   'Roergebakken varken met verse basilicum en oestersaus'),
  (51, 'en', 'Pork with basil',                        'Stir-fried pork with fresh basil and oyster sauce'),
  (52, 'fr', 'Chop Suey au porc',                     'Porc sauté aux légumes variés à la chinoise'),
  (52, 'nl', 'Chop Suey met varken',                   'Roergebakken varken met diverse groenten'),
  (52, 'en', 'Chop suey with pork',                    'Stir-fried pork with assorted vegetables'),
  (53, 'fr', 'Porc aux champignons chinois',           'Porc sauté aux champignons noirs'),
  (53, 'nl', 'Varken met Chinese paddenstoelen',        'Roergebakken varken met zwarte paddenstoelen'),
  (53, 'en', 'Pork with Chinese mushrooms',            'Stir-fried pork with black mushrooms'),
  (54, 'fr', 'Porc à la sauce épicée',                'Porc sauté en sauce pimentée'),
  (54, 'nl', 'Varken met pikante saus',                'Roergebakken varken in pittige saus'),
  (54, 'en', 'Pork with spicy sauce',                  'Stir-fried pork in spicy sauce'),
  (55, 'fr', 'Porc à la sauce au curry',              'Porc sauté en sauce au curry'),
  (55, 'nl', 'Varken met currysaus',                   'Roergebakken varken in currysaus'),
  (55, 'en', 'Pork with curry sauce',                  'Stir-fried pork in curry sauce'),
  (56, 'fr', 'Porc aux légumes mélangés',             'Porc sauté aux légumes frais variés'),
  (56, 'nl', 'Varken met gemengde groenten',            'Roergebakken varken met verse gemengde groenten'),
  (56, 'en', 'Pork with mixed vegetables',             'Stir-fried pork with fresh mixed vegetables'),
  (57, 'fr', 'Beignet de porc à l''ananas sauce aigre-douce', 'Porc frit, ananas, sauce aigre-douce'),
  (57, 'nl', 'Varkenbeignet met ananas en zoetzure saus', 'Gefrituurde varken, ananas, zoetzure saus'),
  (57, 'en', 'Pork fritter with pineapple, sweet-sour sauce', 'Fried pork with pineapple and sweet and sour sauce'),
  (58, 'fr', 'Babi Pangang',                           'Porc rôti sauce rouge aigre-douce, spécialité indonésienne'),
  (58, 'nl', 'Babi Pangang',                           'Geroosterd varken met rode zoetzure saus, Indonesisch specialiteit'),
  (58, 'en', 'Babi Pangang',                           'Roasted pork with sweet-sour red sauce, Indonesian specialty'),
  (59, 'fr', 'Côtelettes de porc rôties',              'Côtelettes de porc marinées et rôties'),
  (59, 'nl', 'Geroosterde varkenskoteletten',           'Gemarineerde en geroosterde varkenskoteletten'),
  (59, 'en', 'Roasted pork chops',                     'Marinated and roasted pork chops'),
  -- DUCK
  (60, 'fr', 'Canard laqué de Pékin',                  'Demi-canard, sauce hoisin, crêpes et poireaux'),
  (60, 'nl', 'Pekingeend',                              'Halve eend, hoisinsaus, pannenkoekjes en prei'),
  (60, 'en', 'Peking duck',                             'Half duck, hoisin sauce, pancakes and leeks'),
  (61, 'fr', 'Canard aux 8 délices',                   'Canard sauté avec poulet, scampis et bœuf, légumes'),
  (61, 'nl', 'Eend met 8 lekkernijen',                  'Gebakken eend met kip, scampi en rund, groenten'),
  (61, 'en', 'Duck with 8 delicacies',                  'Duck sautéed with chicken, scampi and beef, vegetables'),
  (62, 'fr', 'Canard à la sauce d''orange fraîche',    'Canard sauté à la sauce d''orange fraîche'),
  (62, 'nl', 'Eend met verse sinaasappelsaus',           'Gebakken eend met verse sinaasappelsaus'),
  (62, 'en', 'Duck with fresh orange sauce',            'Duck sautéed in fresh orange sauce'),
  (63, 'fr', 'Canard à la sauce épicée',               'Canard sauté en sauce pimentée'),
  (63, 'nl', 'Eend met pikante saus',                   'Gebakken eend in pittige saus'),
  (63, 'en', 'Duck with spicy sauce',                   'Duck sautéed in spicy sauce'),
  (64, 'fr', 'Canard à l''ananas frais',               'Canard sauté à l''ananas frais'),
  (64, 'nl', 'Eend met verse ananas',                   'Gebakken eend met verse ananas'),
  (64, 'en', 'Duck with fresh pineapple',               'Duck sautéed with fresh pineapple'),
  (65, 'fr', 'Canard aux légumes mélangés',            'Canard sauté aux légumes frais variés'),
  (65, 'nl', 'Eend met gemengde groenten',               'Gebakken eend met verse gemengde groenten'),
  (65, 'en', 'Duck with mixed vegetables',              'Duck sautéed with fresh mixed vegetables'),
  -- SCAMPI
  (66, 'fr', 'Scampis au basilic',                      'Scampis sautées au basilic frais'),
  (66, 'nl', 'Scampi met basilicum',                    'Gebakken scampi met verse basilicum'),
  (66, 'en', 'Scampi with basil',                       'Stir-fried scampi with fresh basil'),
  (67, 'fr', 'Chop Suey aux scampis',                   'Scampis sautées aux légumes variés à la chinoise'),
  (67, 'nl', 'Chop Suey met scampi',                    'Roergebakken scampi met diverse groenten'),
  (67, 'en', 'Chop suey with scampi',                   'Stir-fried scampi with assorted vegetables'),
  (68, 'fr', 'Scampis aux champignons chinois',          'Scampis sautées aux champignons noirs'),
  (68, 'nl', 'Scampi met Chinese paddenstoelen',         'Roergebakken scampi met zwarte paddenstoelen'),
  (68, 'en', 'Scampi with Chinese mushrooms',            'Stir-fried scampi with black mushrooms'),
  (69, 'fr', 'Scampis à la sauce épicée',               'Scampis sautées en sauce pimentée'),
  (69, 'nl', 'Scampi met pikante saus',                  'Roergebakken scampi in pittige saus'),
  (69, 'en', 'Scampi with spicy sauce',                  'Stir-fried scampi in spicy sauce'),
  (70, 'fr', 'Scampis à la sauce au curry',             'Scampis sautées en sauce au curry'),
  (70, 'nl', 'Scampi met currysaus',                     'Roergebakken scampi in currysaus'),
  (70, 'en', 'Scampi with curry sauce',                  'Stir-fried scampi in curry sauce'),
  (71, 'fr', 'Scampis aux légumes mélangés',            'Scampis sautées aux légumes frais variés'),
  (71, 'nl', 'Scampi met gemengde groenten',              'Roergebakken scampi met verse gemengde groenten'),
  (71, 'en', 'Scampi with mixed vegetables',             'Stir-fried scampi with fresh mixed vegetables'),
  (72, 'fr', 'Scampis au beurre d''ail',                'Scampis sautées au beurre et à l''ail'),
  (72, 'nl', 'Scampi in knoflookboter',                  'Scampi gebakken in boter en knoflook'),
  (72, 'en', 'Scampi in garlic butter sauce',            'Scampi sautéed in garlic butter sauce'),
  (73, 'fr', 'Beignets de scampis sauce aigre-douce',   'Scampis en tempura, sauce aigre-douce'),
  (73, 'nl', 'Scampibeignets zoetzure saus',             'Scampi in tempura, zoetzure saus'),
  (73, 'en', 'Scampi fritters with sweet-sour sauce',   'Scampi in tempura batter, sweet and sour sauce'),
  -- SEAFOOD
  (74, 'fr', 'Calmars à la sauce épicée',              'Calmars sautés en sauce pimentée'),
  (74, 'nl', 'Inktvis met pikante saus',                'Roergebakken inktvis in pittige saus'),
  (74, 'en', 'Squid with spicy sauce',                  'Stir-fried squid in spicy sauce'),
  (75, 'fr', 'Calmars aux légumes mélangés',           'Calmars sautés aux légumes frais variés'),
  (75, 'nl', 'Inktvis met gemengde groenten',            'Roergebakken inktvis met verse gemengde groenten'),
  (75, 'en', 'Squid with mixed vegetables',             'Stir-fried squid with fresh mixed vegetables'),
  (76, 'fr', 'Gambas grillées façon chef',              'Gambas grillées à la façon du chef'),
  (76, 'nl', 'Gegrilde gambas op chefwijze',             'Gambas gegrild op wijze van de chef'),
  (76, 'en', 'Grilled gambas, chef''s style',           'Gambas grilled chef''s way'),
  (77, 'fr', 'Gambas au beurre d''ail',                 'Gambas sautées au beurre et à l''ail'),
  (77, 'nl', 'Gambas in knoflookboter',                  'Gambas gebakken in boter en knoflook'),
  (77, 'en', 'Gambas in garlic butter',                  'Gambas sautéed in garlic butter'),
  (78, 'fr', 'Sole frite au beurre',                    'Sole de mer entière frite au beurre'),
  (78, 'nl', 'Gebakken zeebot in botersaus',             'Hele zeebot gebakken in botersaus'),
  (78, 'en', 'Fried sea sole in butter sauce',           'Whole sea sole fried in butter sauce'),
  (79, 'fr', 'Sole vapeur à la chinoise',               'Sole de mer entière cuite vapeur à la chinoise'),
  (79, 'nl', 'Gestoomde zeebot op Chinese wijze',        'Hele zeebot gestoomd op Chinese wijze'),
  (79, 'en', 'Steamed sea sole, Chinese style',          'Whole sea sole steamed in Chinese style'),
  (80, 'fr', 'Coquilles St. Jacques à la sauce à l''ail','St. Jacques poêlées à la sauce à l''ail'),
  (80, 'nl', 'Coquilles St. Jacques met knoflooksaus',    'St. Jacques gebakken met knoflooksaus'),
  (80, 'en', 'St. Jacques shells with garlic sauce',     'Scallops pan-fried with garlic sauce'),
  (81, 'fr', 'Coquilles St. Jacques aux légumes',       'St. Jacques poêlées aux légumes variés'),
  (81, 'nl', 'Coquilles St. Jacques met groenten',       'St. Jacques gebakken met gevarieerde groenten'),
  (81, 'en', 'St. Jacques shells with vegetables',       'Scallops pan-fried with vegetables'),
  (82, 'fr', 'Cuisses de grenouilles au beurre et à l''ail', 'Grenouilles sautées au beurre et à l''ail'),
  (82, 'nl', 'Kikkerbillen met boter en knoflook',       'Kikkerbillen gebakken in boter en knoflook'),
  (82, 'en', 'Frog legs with butter and garlic',         'Frog legs sautéed in garlic butter'),
  (83, 'fr', 'Cuisses de grenouilles façon chef',        'Grenouilles préparées à la façon du chef'),
  (83, 'nl', 'Kikkerbillen op chefwijze',                'Kikkerbillen bereid op wijze van de chef'),
  (83, 'en', 'Frog legs, chef''s style',                 'Frog legs prepared chef''s way'),
  -- TI-PAN
  (84, 'fr', 'Ti-Pan poulet',                           'Poulet servi dans un plat chaud Ti-Pan'),
  (84, 'nl', 'Ti-Pan kip',                              'Kip geserveerd in een warm Ti-Pan schaal'),
  (84, 'en', 'Ti-Pan chicken',                          'Chicken served in a hot Ti-Pan dish'),
  (85, 'fr', 'Ti-Pan bœuf',                             'Bœuf servi dans un plat chaud Ti-Pan'),
  (85, 'nl', 'Ti-Pan rund',                              'Rundvlees geserveerd in een warm Ti-Pan schaal'),
  (85, 'en', 'Ti-Pan beef',                              'Beef served in a hot Ti-Pan dish'),
  (86, 'fr', 'Ti-Pan scampis',                          'Scampis servies dans un plat chaud Ti-Pan'),
  (86, 'nl', 'Ti-Pan scampi',                            'Scampi geserveerd in een warm Ti-Pan schaal'),
  (86, 'en', 'Ti-Pan scampi',                            'Scampi served in a hot Ti-Pan dish'),
  (87, 'fr', 'Ti-Pan canard',                           'Canard servi dans un plat chaud Ti-Pan'),
  (87, 'nl', 'Ti-Pan eend',                              'Eend geserveerd in een warm Ti-Pan schaal'),
  (87, 'en', 'Ti-Pan duck',                              'Duck served in a hot Ti-Pan dish'),
  (88, 'fr', 'Ti-Pan maison (viandes et fruits de mer)', 'Assortiment viandes et fruits de mer en Ti-Pan'),
  (88, 'nl', 'Ti-Pan huisstijl (vlees en zeevruchten)',  'Assortiment vlees en zeevruchten in Ti-Pan'),
  (88, 'en', 'Ti-Pan house style (meat and seafood)',    'Assorted meat and seafood in Ti-Pan'),
  (89, 'fr', 'Ti-Pan filet de poulet sauce à l''ail',   'Filet de poulet en Ti-Pan, sauce à l''ail'),
  (89, 'nl', 'Ti-Pan kipfilet met knoflooksaus',         'Kipfilet in Ti-Pan met knoflooksaus'),
  (89, 'en', 'Ti-Pan chicken fillet with garlic sauce',  'Chicken fillet in Ti-Pan with garlic sauce'),
  (90, 'fr', 'Ti-Pan cuisses de grenouilles au beurre et à l''ail', 'Grenouilles en Ti-Pan au beurre et à l''ail'),
  (90, 'nl', 'Ti-Pan kikkerbillen met boter en knoflook','Kikkerbillen in Ti-Pan met boter en knoflook'),
  (90, 'en', 'Ti-Pan frog legs with butter and garlic',  'Frog legs in Ti-Pan with garlic butter'),
  -- CASSEROLES
  (91, 'fr', 'Cassolette de poulet au lait de coco curry rouge',   'Poulet mijoté en cocotte, lait de coco et curry rouge'),
  (91, 'nl', 'Kippencasserole met kokosmelk en rode curry',         'Kip gestoofd in kokosmelk en rode curry'),
  (91, 'en', 'Chicken casserole in coconut milk, red curry',        'Chicken braised in coconut milk and red curry'),
  (92, 'fr', 'Cassolette de bœuf au lait de coco curry rouge',     'Bœuf mijoté en cocotte, lait de coco et curry rouge'),
  (92, 'nl', 'Rundvleesscasserole met kokosmelk en rode curry',      'Rundvlees gestoofd in kokosmelk en rode curry'),
  (92, 'en', 'Beef casserole in coconut milk, red curry',           'Beef braised in coconut milk and red curry'),
  (93, 'fr', 'Cassolette de porc au lait de coco curry rouge',      'Porc mijoté en cocotte, lait de coco et curry rouge'),
  (93, 'nl', 'Varkensscasserole met kokosmelk en rode curry',        'Varken gestoofd in kokosmelk en rode curry'),
  (93, 'en', 'Pork casserole in coconut milk, red curry',           'Pork braised in coconut milk and red curry'),
  (94, 'fr', 'Cassolette de canard au lait de coco curry rouge',    'Canard mijoté en cocotte, lait de coco et curry rouge'),
  (94, 'nl', 'Eendcasserole met kokosmelk en rode curry',            'Eend gestoofd in kokosmelk en rode curry'),
  (94, 'en', 'Duck casserole in coconut milk, red curry',           'Duck braised in coconut milk and red curry'),
  (95, 'fr', 'Cassolette de scampis au lait de coco curry rouge',   'Scampis mijotées en cocotte, lait de coco et curry rouge'),
  (95, 'nl', 'Scampicasserole met kokosmelk en rode curry',          'Scampi gestoofd in kokosmelk en rode curry'),
  (95, 'en', 'Scampi casserole in coconut milk, red curry',         'Scampi braised in coconut milk and red curry'),
  (96, 'fr', 'Cassolette familiale aux vermicelles fins',           'Poulet, bœuf et scampis mijotés aux vermicelles fins'),
  (96, 'nl', 'Familiecasserole met dunne noedels',                   'Kip, rund en scampi gestoofd met dunne noedels'),
  (96, 'en', 'Family casserole with thin noodles',                  'Chicken, beef and scampi braised with thin noodles'),
  (97, 'fr', 'Cassolette de vermicelles et tofu',                   'Tofu et vermicelles fins en bouillon mijoté'),
  (97, 'nl', 'Casserole met dunne noedels en tofu',                  'Tofu en dunne noedels in gestoofd bouillon'),
  (97, 'en', 'Thin noodle and tofu casserole',                      'Tofu and thin noodles in braised broth'),
  -- RICE
  (98,  'fr', 'Riz frit au poulet',                 'Riz sauté au poulet à la chinoise'),
  (98,  'nl', 'Gebakken rijst met kip',              'Roergebakken rijst met kip'),
  (98,  'en', 'Fried rice with chicken',             'Stir-fried rice with chicken'),
  (99,  'fr', 'Riz frit au bœuf',                   'Riz sauté au bœuf à la chinoise'),
  (99,  'nl', 'Gebakken rijst met rund',             'Roergebakken rijst met rundvlees'),
  (99,  'en', 'Fried rice with beef',                'Stir-fried rice with beef'),
  (100, 'fr', 'Riz frit aux scampis',               'Riz sauté aux scampis à la chinoise'),
  (100, 'nl', 'Gebakken rijst met scampi',           'Roergebakken rijst met scampi'),
  (100, 'en', 'Fried rice with scampi',              'Stir-fried rice with scampi'),
  (101, 'fr', 'Riz frit spécial',                   'Riz sauté au bœuf, scampis, poulet et porc'),
  (101, 'nl', 'Speciale gebakken rijst',             'Roergebakken rijst met rund, scampi, kip en varken'),
  (101, 'en', 'Special fried rice',                  'Stir-fried rice with beef, scampi, chicken and pork'),
  (102, 'fr', 'Riz frit au porc',                   'Riz sauté au porc à la chinoise'),
  (102, 'nl', 'Gebakken rijst met varken',           'Roergebakken rijst met varken'),
  (102, 'en', 'Fried rice with pork',                'Stir-fried rice with pork'),
  (103, 'fr', 'Riz frit au canard',                 'Riz sauté au canard à la chinoise'),
  (103, 'nl', 'Gebakken rijst met eend',             'Roergebakken rijst met eend'),
  (103, 'en', 'Fried rice with duck',                'Stir-fried rice with duck'),
  (104, 'fr', 'Riz frit aux légumes',               'Riz sauté aux légumes frais variés'),
  (104, 'nl', 'Gebakken rijst met groenten',         'Roergebakken rijst met verse gemengde groenten'),
  (104, 'en', 'Fried rice with vegetables',          'Stir-fried rice with fresh mixed vegetables'),
  -- NOODLES
  (105, 'fr', 'Nouilles frites au poulet',           'Nouilles sautées au poulet à la chinoise'),
  (105, 'nl', 'Gebakken noedels met kip',            'Roergebakken noedels met kip'),
  (105, 'en', 'Fried noodles with chicken',          'Stir-fried noodles with chicken'),
  (106, 'fr', 'Nouilles frites au bœuf',             'Nouilles sautées au bœuf à la chinoise'),
  (106, 'nl', 'Gebakken noedels met rund',           'Roergebakken noedels met rundvlees'),
  (106, 'en', 'Fried noodles with beef',             'Stir-fried noodles with beef'),
  (107, 'fr', 'Nouilles frites aux scampis',         'Nouilles sautées aux scampis à la chinoise'),
  (107, 'nl', 'Gebakken noedels met scampi',         'Roergebakken noedels met scampi'),
  (107, 'en', 'Fried noodles with scampi',           'Stir-fried noodles with scampi'),
  (108, 'fr', 'Nouilles frites spéciales',           'Nouilles sautées au bœuf, scampis, poulet et porc'),
  (108, 'nl', 'Speciale gebakken noedels',           'Roergebakken noedels met rund, scampi, kip en varken'),
  (108, 'en', 'Special fried noodles',               'Stir-fried noodles with beef, scampi, chicken and pork'),
  (109, 'fr', 'Nouilles frites au porc',             'Nouilles sautées au porc à la chinoise'),
  (109, 'nl', 'Gebakken noedels met varken',         'Roergebakken noedels met varken'),
  (109, 'en', 'Fried noodles with pork',             'Stir-fried noodles with pork'),
  (110, 'fr', 'Nouilles frites au canard',           'Nouilles sautées au canard à la chinoise'),
  (110, 'nl', 'Gebakken noedels met eend',           'Roergebakken noedels met eend'),
  (110, 'en', 'Fried noodles with duck',             'Stir-fried noodles with duck'),
  (111, 'fr', 'Nouilles frites aux légumes',         'Nouilles sautées aux légumes frais variés'),
  (111, 'nl', 'Gebakken noedels met groenten',       'Roergebakken noedels met verse gemengde groenten'),
  (111, 'en', 'Fried noodles with vegetables',       'Stir-fried noodles with fresh mixed vegetables');

COMMIT;
